# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import veriblock_pb2 as veriblock__pb2


class AdminStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPop = channel.unary_unary(
        '/core.Admin/GetPop',
        request_serializer=veriblock__pb2.GetPopRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetPopReply.FromString,
        )
    self.AddNode = channel.unary_unary(
        '/core.Admin/AddNode',
        request_serializer=veriblock__pb2.NodeRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.SetBan = channel.unary_unary(
        '/core.Admin/SetBan',
        request_serializer=veriblock__pb2.SetBanRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.GetInfo = channel.unary_unary(
        '/core.Admin/GetInfo',
        request_serializer=veriblock__pb2.GetInfoRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetInfoReply.FromString,
        )
    self.GetDiagnosticInfo = channel.unary_unary(
        '/core.Admin/GetDiagnosticInfo',
        request_serializer=veriblock__pb2.GetDiagnosticInfoRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetDiagnosticInfoReply.FromString,
        )
    self.RemoveNode = channel.unary_unary(
        '/core.Admin/RemoveNode',
        request_serializer=veriblock__pb2.NodeRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.StopPool = channel.unary_unary(
        '/core.Admin/StopPool',
        request_serializer=veriblock__pb2.StopPoolRequest.SerializeToString,
        response_deserializer=veriblock__pb2.StopPoolReply.FromString,
        )
    self.SubmitPop = channel.unary_unary(
        '/core.Admin/SubmitPop',
        request_serializer=veriblock__pb2.SubmitPopRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.SendCoins = channel.unary_unary(
        '/core.Admin/SendCoins',
        request_serializer=veriblock__pb2.SendCoinsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.SendCoinsReply.FromString,
        )
    self.SendAltChainEndorsement = channel.unary_unary(
        '/core.Admin/SendAltChainEndorsement',
        request_serializer=veriblock__pb2.SendAltChainEndorsementRequest.SerializeToString,
        response_deserializer=veriblock__pb2.SendAltChainEndorsementReply.FromString,
        )
    self.GetBlocks = channel.unary_unary(
        '/core.Admin/GetBlocks',
        request_serializer=veriblock__pb2.GetBlocksRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetBlocksReply.FromString,
        )
    self.StartPool = channel.unary_unary(
        '/core.Admin/StartPool',
        request_serializer=veriblock__pb2.StartPoolRequest.SerializeToString,
        response_deserializer=veriblock__pb2.StartPoolReply.FromString,
        )
    self.RestartPoolWebServer = channel.unary_unary(
        '/core.Admin/RestartPoolWebServer',
        request_serializer=veriblock__pb2.RestartPoolWebServerRequest.SerializeToString,
        response_deserializer=veriblock__pb2.RestartPoolWebServerReply.FromString,
        )
    self.GetHistory = channel.unary_unary(
        '/core.Admin/GetHistory',
        request_serializer=veriblock__pb2.GetHistoryRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetHistoryReply.FromString,
        )
    self.GetBalance = channel.unary_unary(
        '/core.Admin/GetBalance',
        request_serializer=veriblock__pb2.GetBalanceRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetBalanceReply.FromString,
        )
    self.SetAllowed = channel.unary_unary(
        '/core.Admin/SetAllowed',
        request_serializer=veriblock__pb2.SetAllowedRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.ListBanned = channel.unary_unary(
        '/core.Admin/ListBanned',
        request_serializer=veriblock__pb2.ListBannedRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ListBannedReply.FromString,
        )
    self.ListBannedMiners = channel.unary_unary(
        '/core.Admin/ListBannedMiners',
        request_serializer=veriblock__pb2.ListBannedMinersRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ListBannedMinersReply.FromString,
        )
    self.ClearBanned = channel.unary_unary(
        '/core.Admin/ClearBanned',
        request_serializer=veriblock__pb2.ClearBannedRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.ClearBannedMiners = channel.unary_unary(
        '/core.Admin/ClearBannedMiners',
        request_serializer=veriblock__pb2.ClearBannedMinersRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.SubmitBlocks = channel.unary_unary(
        '/core.Admin/SubmitBlocks',
        request_serializer=veriblock__pb2.SubmitBlocksRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.ClearAllowed = channel.unary_unary(
        '/core.Admin/ClearAllowed',
        request_serializer=veriblock__pb2.ClearAllowedRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.GetPeerInfo = channel.unary_unary(
        '/core.Admin/GetPeerInfo',
        request_serializer=veriblock__pb2.GetPeerInfoRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetPeerInfoReply.FromString,
        )
    self.SignMessage = channel.unary_unary(
        '/core.Admin/SignMessage',
        request_serializer=veriblock__pb2.SignMessageRequest.SerializeToString,
        response_deserializer=veriblock__pb2.SignMessageReply.FromString,
        )
    self.ListAllowed = channel.unary_unary(
        '/core.Admin/ListAllowed',
        request_serializer=veriblock__pb2.ListAllowedRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ListAllowedReply.FromString,
        )
    self.BackupWallet = channel.unary_unary(
        '/core.Admin/BackupWallet',
        request_serializer=veriblock__pb2.BackupWalletRequest.SerializeToString,
        response_deserializer=veriblock__pb2.BackupWalletReply.FromString,
        )
    self.ImportWallet = channel.unary_unary(
        '/core.Admin/ImportWallet',
        request_serializer=veriblock__pb2.ImportWalletRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ImportWalletReply.FromString,
        )
    self.GetNewAddress = channel.unary_unary(
        '/core.Admin/GetNewAddress',
        request_serializer=veriblock__pb2.GetNewAddressRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetNewAddressReply.FromString,
        )
    self.GetBlockTimes = channel.unary_unary(
        '/core.Admin/GetBlockTimes',
        request_serializer=veriblock__pb2.GetBlockTimesRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetBlockTimesReply.FromString,
        )
    self.StartSoloPool = channel.unary_unary(
        '/core.Admin/StartSoloPool',
        request_serializer=veriblock__pb2.StartSoloPoolRequest.SerializeToString,
        response_deserializer=veriblock__pb2.StartSoloPoolReply.FromString,
        )
    self.GetBlockchains = channel.unary_unary(
        '/core.Admin/GetBlockchains',
        request_serializer=veriblock__pb2.GetBlockchainsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetBlockchainsReply.FromString,
        )
    self.SetTransactionFee = channel.unary_unary(
        '/core.Admin/SetTransactionFee',
        request_serializer=veriblock__pb2.SetTransactionFeeRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.DumpPrivateKey = channel.unary_unary(
        '/core.Admin/DumpPrivateKey',
        request_serializer=veriblock__pb2.DumpPrivateKeyRequest.SerializeToString,
        response_deserializer=veriblock__pb2.DumpPrivateKeyReply.FromString,
        )
    self.ImportPrivateKey = channel.unary_unary(
        '/core.Admin/ImportPrivateKey',
        request_serializer=veriblock__pb2.ImportPrivateKeyRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ImportPrivateKeyReply.FromString,
        )
    self.SubmitTransactions = channel.unary_unary(
        '/core.Admin/SubmitTransactions',
        request_serializer=veriblock__pb2.SubmitTransactionsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.GetTransactions = channel.unary_unary(
        '/core.Admin/GetTransactions',
        request_serializer=veriblock__pb2.GetTransactionsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetTransactionsReply.FromString,
        )
    self.ValidateAddress = channel.unary_unary(
        '/core.Admin/ValidateAddress',
        request_serializer=veriblock__pb2.ValidateAddressRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ValidateAddressReply.FromString,
        )
    self.GenerateMultisigAddress = channel.unary_unary(
        '/core.Admin/GenerateMultisigAddress',
        request_serializer=veriblock__pb2.GenerateMultisigAddressRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GenerateMultisigAddressReply.FromString,
        )
    self.MakeUnsignedMultisigTx = channel.unary_unary(
        '/core.Admin/MakeUnsignedMultisigTx',
        request_serializer=veriblock__pb2.MakeUnsignedMultisigTxRequest.SerializeToString,
        response_deserializer=veriblock__pb2.MakeUnsignedMultisigTxReply.FromString,
        )
    self.SubmitMultisigTx = channel.unary_unary(
        '/core.Admin/SubmitMultisigTx',
        request_serializer=veriblock__pb2.SubmitMultisigTxRequest.SerializeToString,
        response_deserializer=veriblock__pb2.SubmitMultisigTxReply.FromString,
        )
    self.GetBitcoinBlockIndex = channel.unary_unary(
        '/core.Admin/GetBitcoinBlockIndex',
        request_serializer=veriblock__pb2.GetBitcoinBlockIndexRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.GetBlockTemplate = channel.unary_unary(
        '/core.Admin/GetBlockTemplate',
        request_serializer=veriblock__pb2.GetBlockTemplateRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetBlockTemplateReply.FromString,
        )
    self.GetSignatureIndex = channel.unary_unary(
        '/core.Admin/GetSignatureIndex',
        request_serializer=veriblock__pb2.GetSignatureIndexRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetSignatureIndexReply.FromString,
        )
    self.SetDefaultAddress = channel.unary_unary(
        '/core.Admin/SetDefaultAddress',
        request_serializer=veriblock__pb2.SetDefaultAddressRequest.SerializeToString,
        response_deserializer=veriblock__pb2.SetDefaultAddressReply.FromString,
        )
    self.GetLastBitcoinBlock = channel.unary_unary(
        '/core.Admin/GetLastBitcoinBlock',
        request_serializer=veriblock__pb2.GetLastBitcoinBlockRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetLastBitcoinBlockReply.FromString,
        )
    self.GetProtectedChildren = channel.unary_unary(
        '/core.Admin/GetProtectedChildren',
        request_serializer=veriblock__pb2.GetProtectedChildrenRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetProtectedChildrenReply.FromString,
        )
    self.GetProtectingParents = channel.unary_unary(
        '/core.Admin/GetProtectingParents',
        request_serializer=veriblock__pb2.GetProtectingParentsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetProtectingParentsReply.FromString,
        )
    self.GetWalletTransactions = channel.unary_unary(
        '/core.Admin/GetWalletTransactions',
        request_serializer=veriblock__pb2.GetWalletTransactionsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetWalletTransactionsReply.FromString,
        )
    self.GetEndorsementsOfBlock = channel.unary_unary(
        '/core.Admin/GetEndorsementsOfBlock',
        request_serializer=veriblock__pb2.GetEndorsementsOfBlockRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetEndorsementsOfBlockReply.FromString,
        )
    self.GetPendingTransactions = channel.unary_unary(
        '/core.Admin/GetPendingTransactions',
        request_serializer=veriblock__pb2.GetPendingTransactionsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetPendingTransactionsReply.FromString,
        )
    self.GetPoPEndorsementsInfo = channel.unary_unary(
        '/core.Admin/GetPoPEndorsementsInfo',
        request_serializer=veriblock__pb2.GetPoPEndorsementsInfoRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetPoPEndorsementsInfoReply.FromString,
        )
    self.Ping = channel.unary_unary(
        '/core.Admin/Ping',
        request_serializer=veriblock__pb2.PingRequest.SerializeToString,
        response_deserializer=veriblock__pb2.PingReply.FromString,
        )
    self.GetStateInfo = channel.unary_unary(
        '/core.Admin/GetStateInfo',
        request_serializer=veriblock__pb2.GetStateInfoRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetStateInfoReply.FromString,
        )
    self.GetLastBlock = channel.unary_unary(
        '/core.Admin/GetLastBlock',
        request_serializer=veriblock__pb2.GetLastBlockRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetLastBlockReply.FromString,
        )
    self.ListBlocksSince = channel.unary_unary(
        '/core.Admin/ListBlocksSince',
        request_serializer=veriblock__pb2.ListBlocksSinceRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ListBlocksSinceReply.FromString,
        )
    self.TroubleshootPoPTransactions = channel.unary_unary(
        '/core.Admin/TroubleshootPoPTransactions',
        request_serializer=veriblock__pb2.TroubleshootPoPTransactionsRequest.SerializeToString,
        response_deserializer=veriblock__pb2.TroubleshootPoPTransactionsReply.FromString,
        )
    self.StopNodeCore = channel.unary_unary(
        '/core.Admin/StopNodeCore',
        request_serializer=veriblock__pb2.StopNodeCoreRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.RefreshWalletCache = channel.unary_unary(
        '/core.Admin/RefreshWalletCache',
        request_serializer=veriblock__pb2.RefreshWalletCacheRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.EncryptWallet = channel.unary_unary(
        '/core.Admin/EncryptWallet',
        request_serializer=veriblock__pb2.EncryptWalletRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.DecryptWallet = channel.unary_unary(
        '/core.Admin/DecryptWallet',
        request_serializer=veriblock__pb2.DecryptWalletRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.UnlockWallet = channel.unary_unary(
        '/core.Admin/UnlockWallet',
        request_serializer=veriblock__pb2.UnlockWalletRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.LockWallet = channel.unary_unary(
        '/core.Admin/LockWallet',
        request_serializer=veriblock__pb2.LockWalletRequest.SerializeToString,
        response_deserializer=veriblock__pb2.ProtocolReply.FromString,
        )
    self.DrainAddress = channel.unary_unary(
        '/core.Admin/DrainAddress',
        request_serializer=veriblock__pb2.DrainAddressRequest.SerializeToString,
        response_deserializer=veriblock__pb2.DrainAddressReply.FromString,
        )
    self.GetBalanceUnlockSchedule = channel.unary_unary(
        '/core.Admin/GetBalanceUnlockSchedule',
        request_serializer=veriblock__pb2.GetBalanceUnlockScheduleRequest.SerializeToString,
        response_deserializer=veriblock__pb2.GetBalanceUnlockScheduleReply.FromString,
        )


class AdminServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetBan(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDiagnosticInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopPool(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitPop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCoins(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendAltChainEndorsement(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartPool(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RestartPoolWebServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetAllowed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListBanned(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListBannedMiners(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearBanned(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearBannedMiners(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitBlocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearAllowed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPeerInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SignMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAllowed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BackupWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNewAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockTimes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartSoloPool(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockchains(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetTransactionFee(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DumpPrivateKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImportPrivateKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenerateMultisigAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MakeUnsignedMultisigTx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitMultisigTx(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBitcoinBlockIndex(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBlockTemplate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSignatureIndex(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDefaultAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLastBitcoinBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProtectedChildren(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProtectingParents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetWalletTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEndorsementsOfBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPendingTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPoPEndorsementsInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStateInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLastBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListBlocksSince(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TroubleshootPoPTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopNodeCore(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RefreshWalletCache(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EncryptWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DecryptWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnlockWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LockWallet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DrainAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBalanceUnlockSchedule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdminServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPop': grpc.unary_unary_rpc_method_handler(
          servicer.GetPop,
          request_deserializer=veriblock__pb2.GetPopRequest.FromString,
          response_serializer=veriblock__pb2.GetPopReply.SerializeToString,
      ),
      'AddNode': grpc.unary_unary_rpc_method_handler(
          servicer.AddNode,
          request_deserializer=veriblock__pb2.NodeRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'SetBan': grpc.unary_unary_rpc_method_handler(
          servicer.SetBan,
          request_deserializer=veriblock__pb2.SetBanRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'GetInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetInfo,
          request_deserializer=veriblock__pb2.GetInfoRequest.FromString,
          response_serializer=veriblock__pb2.GetInfoReply.SerializeToString,
      ),
      'GetDiagnosticInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDiagnosticInfo,
          request_deserializer=veriblock__pb2.GetDiagnosticInfoRequest.FromString,
          response_serializer=veriblock__pb2.GetDiagnosticInfoReply.SerializeToString,
      ),
      'RemoveNode': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveNode,
          request_deserializer=veriblock__pb2.NodeRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'StopPool': grpc.unary_unary_rpc_method_handler(
          servicer.StopPool,
          request_deserializer=veriblock__pb2.StopPoolRequest.FromString,
          response_serializer=veriblock__pb2.StopPoolReply.SerializeToString,
      ),
      'SubmitPop': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitPop,
          request_deserializer=veriblock__pb2.SubmitPopRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'SendCoins': grpc.unary_unary_rpc_method_handler(
          servicer.SendCoins,
          request_deserializer=veriblock__pb2.SendCoinsRequest.FromString,
          response_serializer=veriblock__pb2.SendCoinsReply.SerializeToString,
      ),
      'SendAltChainEndorsement': grpc.unary_unary_rpc_method_handler(
          servicer.SendAltChainEndorsement,
          request_deserializer=veriblock__pb2.SendAltChainEndorsementRequest.FromString,
          response_serializer=veriblock__pb2.SendAltChainEndorsementReply.SerializeToString,
      ),
      'GetBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlocks,
          request_deserializer=veriblock__pb2.GetBlocksRequest.FromString,
          response_serializer=veriblock__pb2.GetBlocksReply.SerializeToString,
      ),
      'StartPool': grpc.unary_unary_rpc_method_handler(
          servicer.StartPool,
          request_deserializer=veriblock__pb2.StartPoolRequest.FromString,
          response_serializer=veriblock__pb2.StartPoolReply.SerializeToString,
      ),
      'RestartPoolWebServer': grpc.unary_unary_rpc_method_handler(
          servicer.RestartPoolWebServer,
          request_deserializer=veriblock__pb2.RestartPoolWebServerRequest.FromString,
          response_serializer=veriblock__pb2.RestartPoolWebServerReply.SerializeToString,
      ),
      'GetHistory': grpc.unary_unary_rpc_method_handler(
          servicer.GetHistory,
          request_deserializer=veriblock__pb2.GetHistoryRequest.FromString,
          response_serializer=veriblock__pb2.GetHistoryReply.SerializeToString,
      ),
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=veriblock__pb2.GetBalanceRequest.FromString,
          response_serializer=veriblock__pb2.GetBalanceReply.SerializeToString,
      ),
      'SetAllowed': grpc.unary_unary_rpc_method_handler(
          servicer.SetAllowed,
          request_deserializer=veriblock__pb2.SetAllowedRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'ListBanned': grpc.unary_unary_rpc_method_handler(
          servicer.ListBanned,
          request_deserializer=veriblock__pb2.ListBannedRequest.FromString,
          response_serializer=veriblock__pb2.ListBannedReply.SerializeToString,
      ),
      'ListBannedMiners': grpc.unary_unary_rpc_method_handler(
          servicer.ListBannedMiners,
          request_deserializer=veriblock__pb2.ListBannedMinersRequest.FromString,
          response_serializer=veriblock__pb2.ListBannedMinersReply.SerializeToString,
      ),
      'ClearBanned': grpc.unary_unary_rpc_method_handler(
          servicer.ClearBanned,
          request_deserializer=veriblock__pb2.ClearBannedRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'ClearBannedMiners': grpc.unary_unary_rpc_method_handler(
          servicer.ClearBannedMiners,
          request_deserializer=veriblock__pb2.ClearBannedMinersRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'SubmitBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitBlocks,
          request_deserializer=veriblock__pb2.SubmitBlocksRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'ClearAllowed': grpc.unary_unary_rpc_method_handler(
          servicer.ClearAllowed,
          request_deserializer=veriblock__pb2.ClearAllowedRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'GetPeerInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetPeerInfo,
          request_deserializer=veriblock__pb2.GetPeerInfoRequest.FromString,
          response_serializer=veriblock__pb2.GetPeerInfoReply.SerializeToString,
      ),
      'SignMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SignMessage,
          request_deserializer=veriblock__pb2.SignMessageRequest.FromString,
          response_serializer=veriblock__pb2.SignMessageReply.SerializeToString,
      ),
      'ListAllowed': grpc.unary_unary_rpc_method_handler(
          servicer.ListAllowed,
          request_deserializer=veriblock__pb2.ListAllowedRequest.FromString,
          response_serializer=veriblock__pb2.ListAllowedReply.SerializeToString,
      ),
      'BackupWallet': grpc.unary_unary_rpc_method_handler(
          servicer.BackupWallet,
          request_deserializer=veriblock__pb2.BackupWalletRequest.FromString,
          response_serializer=veriblock__pb2.BackupWalletReply.SerializeToString,
      ),
      'ImportWallet': grpc.unary_unary_rpc_method_handler(
          servicer.ImportWallet,
          request_deserializer=veriblock__pb2.ImportWalletRequest.FromString,
          response_serializer=veriblock__pb2.ImportWalletReply.SerializeToString,
      ),
      'GetNewAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GetNewAddress,
          request_deserializer=veriblock__pb2.GetNewAddressRequest.FromString,
          response_serializer=veriblock__pb2.GetNewAddressReply.SerializeToString,
      ),
      'GetBlockTimes': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockTimes,
          request_deserializer=veriblock__pb2.GetBlockTimesRequest.FromString,
          response_serializer=veriblock__pb2.GetBlockTimesReply.SerializeToString,
      ),
      'StartSoloPool': grpc.unary_unary_rpc_method_handler(
          servicer.StartSoloPool,
          request_deserializer=veriblock__pb2.StartSoloPoolRequest.FromString,
          response_serializer=veriblock__pb2.StartSoloPoolReply.SerializeToString,
      ),
      'GetBlockchains': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockchains,
          request_deserializer=veriblock__pb2.GetBlockchainsRequest.FromString,
          response_serializer=veriblock__pb2.GetBlockchainsReply.SerializeToString,
      ),
      'SetTransactionFee': grpc.unary_unary_rpc_method_handler(
          servicer.SetTransactionFee,
          request_deserializer=veriblock__pb2.SetTransactionFeeRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'DumpPrivateKey': grpc.unary_unary_rpc_method_handler(
          servicer.DumpPrivateKey,
          request_deserializer=veriblock__pb2.DumpPrivateKeyRequest.FromString,
          response_serializer=veriblock__pb2.DumpPrivateKeyReply.SerializeToString,
      ),
      'ImportPrivateKey': grpc.unary_unary_rpc_method_handler(
          servicer.ImportPrivateKey,
          request_deserializer=veriblock__pb2.ImportPrivateKeyRequest.FromString,
          response_serializer=veriblock__pb2.ImportPrivateKeyReply.SerializeToString,
      ),
      'SubmitTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitTransactions,
          request_deserializer=veriblock__pb2.SubmitTransactionsRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'GetTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactions,
          request_deserializer=veriblock__pb2.GetTransactionsRequest.FromString,
          response_serializer=veriblock__pb2.GetTransactionsReply.SerializeToString,
      ),
      'ValidateAddress': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateAddress,
          request_deserializer=veriblock__pb2.ValidateAddressRequest.FromString,
          response_serializer=veriblock__pb2.ValidateAddressReply.SerializeToString,
      ),
      'GenerateMultisigAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GenerateMultisigAddress,
          request_deserializer=veriblock__pb2.GenerateMultisigAddressRequest.FromString,
          response_serializer=veriblock__pb2.GenerateMultisigAddressReply.SerializeToString,
      ),
      'MakeUnsignedMultisigTx': grpc.unary_unary_rpc_method_handler(
          servicer.MakeUnsignedMultisigTx,
          request_deserializer=veriblock__pb2.MakeUnsignedMultisigTxRequest.FromString,
          response_serializer=veriblock__pb2.MakeUnsignedMultisigTxReply.SerializeToString,
      ),
      'SubmitMultisigTx': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitMultisigTx,
          request_deserializer=veriblock__pb2.SubmitMultisigTxRequest.FromString,
          response_serializer=veriblock__pb2.SubmitMultisigTxReply.SerializeToString,
      ),
      'GetBitcoinBlockIndex': grpc.unary_unary_rpc_method_handler(
          servicer.GetBitcoinBlockIndex,
          request_deserializer=veriblock__pb2.GetBitcoinBlockIndexRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'GetBlockTemplate': grpc.unary_unary_rpc_method_handler(
          servicer.GetBlockTemplate,
          request_deserializer=veriblock__pb2.GetBlockTemplateRequest.FromString,
          response_serializer=veriblock__pb2.GetBlockTemplateReply.SerializeToString,
      ),
      'GetSignatureIndex': grpc.unary_unary_rpc_method_handler(
          servicer.GetSignatureIndex,
          request_deserializer=veriblock__pb2.GetSignatureIndexRequest.FromString,
          response_serializer=veriblock__pb2.GetSignatureIndexReply.SerializeToString,
      ),
      'SetDefaultAddress': grpc.unary_unary_rpc_method_handler(
          servicer.SetDefaultAddress,
          request_deserializer=veriblock__pb2.SetDefaultAddressRequest.FromString,
          response_serializer=veriblock__pb2.SetDefaultAddressReply.SerializeToString,
      ),
      'GetLastBitcoinBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetLastBitcoinBlock,
          request_deserializer=veriblock__pb2.GetLastBitcoinBlockRequest.FromString,
          response_serializer=veriblock__pb2.GetLastBitcoinBlockReply.SerializeToString,
      ),
      'GetProtectedChildren': grpc.unary_unary_rpc_method_handler(
          servicer.GetProtectedChildren,
          request_deserializer=veriblock__pb2.GetProtectedChildrenRequest.FromString,
          response_serializer=veriblock__pb2.GetProtectedChildrenReply.SerializeToString,
      ),
      'GetProtectingParents': grpc.unary_unary_rpc_method_handler(
          servicer.GetProtectingParents,
          request_deserializer=veriblock__pb2.GetProtectingParentsRequest.FromString,
          response_serializer=veriblock__pb2.GetProtectingParentsReply.SerializeToString,
      ),
      'GetWalletTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetWalletTransactions,
          request_deserializer=veriblock__pb2.GetWalletTransactionsRequest.FromString,
          response_serializer=veriblock__pb2.GetWalletTransactionsReply.SerializeToString,
      ),
      'GetEndorsementsOfBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetEndorsementsOfBlock,
          request_deserializer=veriblock__pb2.GetEndorsementsOfBlockRequest.FromString,
          response_serializer=veriblock__pb2.GetEndorsementsOfBlockReply.SerializeToString,
      ),
      'GetPendingTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetPendingTransactions,
          request_deserializer=veriblock__pb2.GetPendingTransactionsRequest.FromString,
          response_serializer=veriblock__pb2.GetPendingTransactionsReply.SerializeToString,
      ),
      'GetPoPEndorsementsInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetPoPEndorsementsInfo,
          request_deserializer=veriblock__pb2.GetPoPEndorsementsInfoRequest.FromString,
          response_serializer=veriblock__pb2.GetPoPEndorsementsInfoReply.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=veriblock__pb2.PingRequest.FromString,
          response_serializer=veriblock__pb2.PingReply.SerializeToString,
      ),
      'GetStateInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetStateInfo,
          request_deserializer=veriblock__pb2.GetStateInfoRequest.FromString,
          response_serializer=veriblock__pb2.GetStateInfoReply.SerializeToString,
      ),
      'GetLastBlock': grpc.unary_unary_rpc_method_handler(
          servicer.GetLastBlock,
          request_deserializer=veriblock__pb2.GetLastBlockRequest.FromString,
          response_serializer=veriblock__pb2.GetLastBlockReply.SerializeToString,
      ),
      'ListBlocksSince': grpc.unary_unary_rpc_method_handler(
          servicer.ListBlocksSince,
          request_deserializer=veriblock__pb2.ListBlocksSinceRequest.FromString,
          response_serializer=veriblock__pb2.ListBlocksSinceReply.SerializeToString,
      ),
      'TroubleshootPoPTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.TroubleshootPoPTransactions,
          request_deserializer=veriblock__pb2.TroubleshootPoPTransactionsRequest.FromString,
          response_serializer=veriblock__pb2.TroubleshootPoPTransactionsReply.SerializeToString,
      ),
      'StopNodeCore': grpc.unary_unary_rpc_method_handler(
          servicer.StopNodeCore,
          request_deserializer=veriblock__pb2.StopNodeCoreRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'RefreshWalletCache': grpc.unary_unary_rpc_method_handler(
          servicer.RefreshWalletCache,
          request_deserializer=veriblock__pb2.RefreshWalletCacheRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'EncryptWallet': grpc.unary_unary_rpc_method_handler(
          servicer.EncryptWallet,
          request_deserializer=veriblock__pb2.EncryptWalletRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'DecryptWallet': grpc.unary_unary_rpc_method_handler(
          servicer.DecryptWallet,
          request_deserializer=veriblock__pb2.DecryptWalletRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'UnlockWallet': grpc.unary_unary_rpc_method_handler(
          servicer.UnlockWallet,
          request_deserializer=veriblock__pb2.UnlockWalletRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'LockWallet': grpc.unary_unary_rpc_method_handler(
          servicer.LockWallet,
          request_deserializer=veriblock__pb2.LockWalletRequest.FromString,
          response_serializer=veriblock__pb2.ProtocolReply.SerializeToString,
      ),
      'DrainAddress': grpc.unary_unary_rpc_method_handler(
          servicer.DrainAddress,
          request_deserializer=veriblock__pb2.DrainAddressRequest.FromString,
          response_serializer=veriblock__pb2.DrainAddressReply.SerializeToString,
      ),
      'GetBalanceUnlockSchedule': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalanceUnlockSchedule,
          request_deserializer=veriblock__pb2.GetBalanceUnlockScheduleRequest.FromString,
          response_serializer=veriblock__pb2.GetBalanceUnlockScheduleReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'core.Admin', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
